//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS.Domain.SharedKernel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCS.Domain.SharedKernel.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmação de senha é obrigatória..
        /// </summary>
        public static string ConfirmarSenhaObrigatoria {
            get {
                return ResourceManager.GetString("ConfirmarSenhaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD é obrigatório..
        /// </summary>
        public static string DDDObrigatorio {
            get {
                return ResourceManager.GetString("DDDObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD em tamanho incorreto..
        /// </summary>
        public static string DDDTamanhoInvalido {
            get {
                return ResourceManager.GetString("DDDTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail em formato inválido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já existente..
        /// </summary>
        public static string EmailJaExiste {
            get {
                return ResourceManager.GetString("EmailJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string EmailObrigatorio {
            get {
                return ResourceManager.GetString("EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail em tamanho incorreto..
        /// </summary>
        public static string EmailTamanhoIncorreto {
            get {
                return ResourceManager.GetString("EmailTamanhoIncorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número é obrigatório..
        /// </summary>
        public static string NumeroObrigatorio {
            get {
                return ResourceManager.GetString("NumeroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número em tamanho incorreto..
        /// </summary>
        public static string NumeroTamanhoInvalido {
            get {
                return ResourceManager.GetString("NumeroTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        public static string SenhaObrigatoria {
            get {
                return ResourceManager.GetString("SenhaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas são iguais..
        /// </summary>
        public static string SenhasIguais {
            get {
                return ResourceManager.GetString("SenhasIguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho da senha não corresponde..
        /// </summary>
        public static string SenhaTamanhoInvalido {
            get {
                return ResourceManager.GetString("SenhaTamanhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente números..
        /// </summary>
        public static string SomenteNumero {
            get {
                return ResourceManager.GetString("SomenteNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário é obrigatório..
        /// </summary>
        public static string UsuarioObrigatorio {
            get {
                return ResourceManager.GetString("UsuarioObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos..
        /// </summary>
        public static string UsuarioSenhaInvalido {
            get {
                return ResourceManager.GetString("UsuarioSenhaInvalido", resourceCulture);
            }
        }
    }
}
